### ISSUE TITLE
How do I change my profile to "Grid View"?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#10]
This was not addressed in the specs

**Comment by CodySwannGT** [comment]
@smummolo leave out for MVP?

**Comment by smummolo** [comment]
leave out for mvp - there should be an icon set for this but its hardly critical functionality

**Comment by adamespn** [comment]
I'm hearing we should do nothing here.

**Comment by smummolo** [comment]
nothing
