### ISSUE TITLE
Take out Expiration Timer in creation screen

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#102]
Talked to Alex and Bob about the Expiration Timer on the war creation screen, and the decision is to take it out from the MVP. The Remind button in the Pending Wars screen (#96 ) should for now fulfill the use case of reminding participants to take action.

**Comment by jiakeliu** [comment]
Here's how the creation screen looks like without the expiration timer:

![newbet](https://cloud.githubusercontent.com/assets/1039583/7576407/083a6776-f7f2-11e4-9772-4d8635a11acc.jpg)

Here's the PSD file: https://www.dropbox.com/s/7uvven7v6v8ufjv/newBet.psd?dl=0

**Comment by husseinm** [comment]
Are we sure we want to do this? The mockups have this feature.

**Comment by jiakeliu** [comment]
@husseinm yes, let's take this out for now.

**Comment by jiakeliu** [comment]
@husseinm please match the bet creation screen to the screenshot above, including taking out the Portrait "You" part in the top left corner.

**Comment by husseinm** [comment]
I just redid the design according to the PSD above. I also implemented the privacy button, but the privacy feature still needs to be implemented server side. So everything has been fixed by the latest commit

**Comment by jiakeliu** [comment]
Mahdi, please assign to me before closing.
