### ISSUE TITLE
Winner indication

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#103]
When a Thumbwar closes, the winner should be indicated with a clear visual cue (like a crown on the portrait), and other users should no longer be able to take sides. Commenting should still be allowed.

@rand027 could you try mocking up the visual cue for the winner?

**Comment by husseinm** [comment]
I believe this is already planned in the current Photoshop mockups?

**Comment by jiakeliu** [comment]
No, still waiting on @rand027  to mock it up.

**Comment by jiakeliu** [comment]
Waiting on PT to mock it up.

**Comment by husseinm** [comment]
Done.

**Comment by jiakeliu** [comment]
Don't see the Trophy/Crown showing up near the user portrait?
