### ISSUE TITLE
War Details screen

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#113]
The layout is absolute and currently not suitable for device screens - use autolayout to correct the screen.

**Comment by husseinm** [comment]
The design's only current issue is the viewing of the ellipses. Should they be visible to everyone? Should they only do something when the intended viewer pushes them? Beyond that it pushes to the server, functions properly, and matches the design.

**Comment by jiakeliu** [comment]
Ellipses should show up for everyone. There should be a drop down menu
after tapping the ellipses, and for participants an item should be "Declare
Winner", which doesn't show up for anyone else.

On Sunday, June 7, 2015, Mahdi Hussein <notifications@github.com> wrote:

> The design's only current issue is the viewing of the ellipses. Should
> they be visible to everyone? Should they only do something when the
> intended viewer pushes them? Beyond that it pushes to the server, functions
> properly, and matches the design.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/113#issuecomment-109820782>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jiakeliu** [comment]
For everyone else, the dropdown menu from the ellipses should show "Report Inappropriate War" when @CodySwannGT can implement that in the backend. This is beyond the scope of the MVP, but feel free to implement the item in the front end and just have a modal window that says "Thank you for reporting!".

**Comment by jiakeliu** [comment]
@husseinm per discussion in #11, please remove "Follow this Thumbwar" and just have "Report this Thumbwar" as a place holder item in the ellipses drop-down.
