### ISSUE TITLE
Who Won page

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#114]
Needs to be implemented

**Comment by husseinm** [comment]
Same as the Results page...

**Comment by jiakeliu** [comment]
See comments in tickets for the Results page and War Details page.

**Comment by jiakeliu** [comment]
Hey @husseinm is this a duplicate ticket of #75?

**Comment by husseinm** [comment]
Yes

**Comment by jiakeliu** [comment]
Closing this ticket out. Please use #75 instead.
