### ISSUE TITLE
Implement Results page

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#115]
implement the results page

**Comment by husseinm** [comment]
I implemented it to the point where anyone can reach a war's result pages by the ellipses. Anyone can currently also request to close the war though it does not hit the server so no one else sees the war closed - The purpose of the results page currently is to make sure they adhere to the intended design as requested, if I get the green-light I will hook the API to those buttons and make them send to the server.

**Comment by husseinm** [comment]
Also how should the ellipses on the war detail page work?

**Comment by jiakeliu** [comment]
Replied to the other ticket

On Sunday, June 7, 2015, Mahdi Hussein <notifications@github.com> wrote:

> Also how should the ellipses on the war detail page work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/115#issuecomment-109820455>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jiakeliu** [comment]
Ellipses should show up for everyone. There should be a drop down menu
after tapping the ellipses, and for participants an item should be "Declare
Winner", which doesn't show up for anyone else.

**Comment by jiakeliu** [comment]
The Results page should only show up on User B's screen after User A's submission from the "Who Won" page.

**Comment by jiakeliu** [comment]
Please use #78 instead.
