### ISSUE TITLE
Implement the followers page

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#116]
Implement the followers page

**Comment by jiakeliu** [comment]
@husseinm how do i view the followers page? shouldn't I be able to see it if I tap on someone's Follower/Following count?

**Comment by husseinm** [comment]
Followers page was intended as the search page, I believe this was a duplicate

Do you want to list users on click of followers/following?

**Comment by jiakeliu** [comment]
Ah, I misunderstood this ticket then. Should we start another ticket for Followers/Following? Or can you just use this ticket?

**Comment by husseinm** [comment]
No Problem, this ticket will work.

**Comment by jiakeliu** [comment]
-Use Results page design
-"Results" change to specific "Following" or "Followers" text
-Bleed to the edge
-change "Tap for Profile" to show "@username"

**Comment by jiakeliu** [comment]
App crashes when I tap someone's profile in the Following/Folower list.
