### ISSUE TITLE
If I'm looking at a ThumbWar that Josh created with Bob as the opponent, where do I see Bob's name?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#12]
This was not addressed in the specs

**Comment by CodySwannGT** [comment]
@smummolo - leave out for mvp?

**Comment by smummolo** [comment]
Let's do first names in the post header: "Josh Vs. Bob     13days ago"

**Comment by adamespn** [comment]
Is this for all wars, even the ones that the user is a participant in? Or should it say "You V Cody", etc.?

**Comment by smummolo** [comment]
You V Cody in my wars works great.

**Comment by CodySwannGT** [comment]
I think you circulated an entirely different design that everyone really liked.

I think the only thing I asked for on that is if you could make a version of that design in which the full 160 characters were used so we could see how to shrink the text down.

**Comment by smummolo** [comment]
sorry - here you go!

https://www.dropbox.com/sh/eydi2c2v9se9t8o/AADdmlEyRZwpGWuGs5qceMVga?dl=0

**Comment by adamespn** [comment]
I can move the avatars and the names like in the attachment. Note that there is no longer a war pic, so some of the design elements may not be necessary.

**Comment by jiakeliu** [comment]
In comments, Alex's name becomes AlexNocifera12. Instead of assigning the username as a concatenated full name + number increment, should we allow users to assign their own username just like a Twitter handle? In that case, the unique username is displayed in the post header instead of seeing an entire feed of different Bob's and Alex's.

**Comment by adamespn** [comment]
We could. If you want to do that, you would move this ticket to the backlog, provide the change information, (potential discussion follows) and then reassign to a sprint/iteration.

**Comment by jiakeliu** [comment]
Let's go with this change for now, and we can create another ticket implementing the username. This ticket is just referring to displaying the name of the poster, which is fine.

**Comment by adamespn** [comment]
For clarity,

I'm closing this ticket as a ticket that simply requires "You V Cody" or "Joe V John", etc.
The avatar changes are addressed in a different ticket even though they are referenced here.
