### ISSUE TITLE
Show image preview after adding a picture in New War screen

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#123]
Currently the "Attach Image" tab below the "What's your bet?" field remains static after attaching an image. 

Instead, the tab should show a preview of the image confined/cropped to the size of the tab, and when a user clicks on the image a modal window should pop up giving a full view of the image with an "X" at the top right to delete the image, in case the user wants to add another image instead.

**Comment by jiakeliu** [comment]
After attaching an image, the bet creation screen should look something like this (stacked cards effect):

![screenshot 2015-07-08 19 13 16](https://cloud.githubusercontent.com/assets/1039583/8586802/f6205404-25a7-11e5-9def-faa0fa4cbc53.png)

When user taps the image portion, a full preview of the image pops up with a "Remove" button overlaying the bottom of the image. Tapping it removes the image attachment and returns the preview tab to the state with the "camera" icon so a user can attach a new image.

**Comment by husseinm** [comment]
Change accept challenge
