### ISSUE TITLE
War detail view "stake" bar is pushed to the right

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#124]
The "Stake" bar should in the war detail view should look like the one in Home view, where it spans the entire row instead of right justified.

**Comment by husseinm** [comment]
This sounds outdated, can you clarify?

**Comment by jiakeliu** [comment]
See the red arrow. This blue bar should be stretched across the screen just like how it looks like in the Home feed.

![img_1157](https://cloud.githubusercontent.com/assets/1039583/8586779/bfc81cde-25a7-11e5-86cd-8f579745b546.PNG)
