### ISSUE TITLE
Ability to challenge mutual followers

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#127]
Currently a user can't challenge a follower. We need to implement this.

**Comment by jiakeliu** [comment]
@CodySwannGT Can we add in this capability since we have the follower system in place now?

**Comment by CodySwannGT** [comment]
There exists an API method today where you can get a list of people who are following you. That would need to be incorporated into the look ahead.

**Comment by jiakeliu** [comment]
@husseinm sounds like a front-end change?

**Comment by husseinm** [comment]
Yup.

**Comment by husseinm** [comment]
Okay, it is implemented in the latest build now. Everything should also be faster as far as autocomplete goes.

**Comment by jiakeliu** [comment]
The intended behavior is that you can only challenge people who also followed you back. Right now I can challenge a user as long as I follow him. Can we fix, @husseinm ?
