### ISSUE TITLE
Need high res icons for notification page

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#132]

**Comment by jiakeliu** [comment]
Also need the AB logo in War creation screen

**Comment by jiakeliu** [comment]
Alerts Page Speech Bubble (For comments alert)

![iconmonstr-speech-bubble-14-icon-256](https://cloud.githubusercontent.com/assets/1039583/8716877/3108a4fc-2b4a-11e5-8316-68dd31e7268a.png)

**Comment by jiakeliu** [comment]
Smartphone logo (to replace AB: )
![iconmonstr-smartphone-4-icon-256](https://cloud.githubusercontent.com/assets/1039583/8716933/c2487b68-2b4a-11e5-9678-e25638a826bc.png)

**Comment by jiakeliu** [comment]
@husseinm what other alert icons do you need besides the speech bubble?

**Comment by husseinm** [comment]
On 7/16/15 2:42 AM, Jiake Liu wrote:
>
> @husseinm <https://github.com/husseinm> what other alert icons do you 
> need besides the speech bubble?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/132#issuecomment-121848951>.
>
The Check mark and the Following icons. (The icons with a circle + check 
mark and the icon with person and a plus on top - these are fallback 
icons in case a users profile pic fails to upload)

Do we also want a facebook icon instead of FB: and a TW icon instead of 
TW: on the challenge? I can pull those icons from the web or from our 
app pic...

**Comment by jiakeliu** [comment]
Please read the comments in the ticket about the AB: and FB: icons. We are removing the FB option altogether (you can't challenge a FB friend who is not already on TW). 

Instead of TW icon, use user profile pic.

Will get you the check mark and follower icons

**Comment by husseinm** [comment]
Sorry forgot about that, I actually already removed the FB option...

**Comment by jiakeliu** [comment]
Just emailed you check mark and follower icons

**Comment by husseinm** [comment]
Got everything - looking good.

**Comment by husseinm** [comment]
Hey just discovered that I also need a single comment bubble (the home feed bubble) and the unwind button  (the back arrow) and the ellipses. Can you please also get those? Sorry for not noticing it early.

**Comment by jiakeliu** [comment]
Mahdi I'm occupied today with my day job, can you go to monstr icon and
search for those logos? That's what I did for the other logos

On Thursday, July 16, 2015, Mahdi Hussein <notifications@github.com> wrote:

> Assigned #132
> <https://github.com/gunnertech/thumbwar-ios-client/issues/132> to
> @jiakeliu <https://github.com/jiakeliu>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/132#event-357861881>
> .
>


-- 
Sent from Gmail Mobile

**Comment by husseinm** [comment]
Gotcha, no problem.
