### ISSUE TITLE
Animation change

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#141]
When tapping on a war, the war detail screen displays with a "Slide Up" animation. Can we use "Slide Left" animation instead?  So the screen enters from the right side, and when the user taps the back arrow the screen exits to the right side.

**Comment by husseinm** [comment]
I don't have that option as a transition, the ones available I have in this video here.

Sorry for the youtube quality encoding, it got downscaled by google. It is shared privately with you:
https://youtu.be/OfZI7O0GRXY

**Comment by jiakeliu** [comment]
Can you check out bullet points 3 and 4 in this article and let me know if this is an easy change? This item is just a nice-to-have, not high priority:

http://mathewsanders.com/animated-transitions-in-swift/

**Comment by husseinm** [comment]
On 7/15/15 6:22 PM, Jiake Liu wrote:
>
> Can you check out bullet points 3 and 4 in this article and let me 
> know if this is an easy change? This item is just a nice-to-have, not 
> high priority:
>
> http://mathewsanders.com/animated-transitions-in-swift/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/141#issuecomment-121766416>.
>
Well I never knew about those. So it is possible, will do.

**Comment by jiakeliu** [comment]
It's under the Custom Transition Animations header
