### ISSUE TITLE
"All" and "Me" toggle

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#147]
Per email conversation, let's add a toggle at the top of the public feed that toggles between "All" and "Me", which shows all wars and only my wars respectively.

The same toggle is also in the Profile page, which also updates the counters for wins, loses, draws, and actives between you and one specific user. So if you go to Bobs profile page, you can toggle "All" and  "Me" to see all his wars and wars only with me.

**Comment by jiakeliu** [comment]
@husseinm This ticket is a priority

**Comment by husseinm** [comment]
I am adding the home feed now.

I currently do not have the ability to retreive wars between you and a specific person, much less the wins/losses and pushes. That requires a server change...
