### ISSUE TITLE
Modify "Who Won" screen to match war detail top bar

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#150]
Update the "Who Won" screen top slider to the new "VS" top bar in the war detail view.

**Comment by husseinm** [comment]
On 7/20/15 3:59 AM, Jiake Liu wrote:
>
> Assigned #150 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/150> to 
> @husseinm <https://github.com/husseinm>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/150#event-359737707>.
>
Already done Jiake...

**Comment by jiakeliu** [comment]
Who Won screen still has the slider instead of how it looks on the home feed or detail view?

**Comment by husseinm** [comment]
Will do in this release
On Jul 21, 2015 4:52 AM, Jiake Liu <notifications@github.com> wrote:Who Won screen still has the slider instead of how it looks on the home feed or detail view?

**Comment by jiakeliu** [comment]
Did you not sleep or you already woke up?

**Comment by husseinm** [comment]
Not sleep - HackerNews is too interesting...
On Jul 21, 2015 4:59 AM, Jiake Liu <notifications@github.com> wrote:Did you not sleep or you already woke up?
