### ISSUE TITLE
Popups on App start

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#155]
1. War Acceptance
2. Winner Declared (Evidence)
3. Won Occurred

1 is already implemented

**Comment by husseinm** [comment]
All with exception of 3 are done.

**Comment by jiakeliu** [comment]
@husseinm we still can't have the Won Occured popup?

**Comment by husseinm** [comment]
It is now working. The only issue with popups as a whole is that they 
only work when your war is in the feed.

On 7/29/2015 6:39 AM, Jiake Liu wrote:
>
> @husseinm <https://github.com/husseinm> we still can't have the Won 
> Occured popup?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/155#issuecomment-125915786>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in
