### ISSUE TITLE
What do we do if there is an actual push?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#18]
Right now, the spec says:

"If the challenger and the opponent agree on the outcome, that is the outcome. If they don't agree, it's a push"

The options are "Challenger Won" and "Opponent Won"

What happens if there is an actual push?

Right now, the two sides would have to differ in order for that to become a reality.

Shouldn't there be a third option "Push" that both sides can choose?

**Comment by DaryMerckensGT** [comment]
"If the challenger and the opponent agree on the outcome, that is the outcome. If they don't agree, it's a push"

Did I miss a new version of the spec? Because that's the dumbest fucking thing I've ever heard.

**Comment by CodySwannGT** [comment]
It's a bit hard to tell because there is a lot in the specs that doesn't have a mock but this is what we were going off of: https://www.dropbox.com/s/c09pgfgings2b1d/Screenshot%202015-01-30%2020.41.59.png?dl=0

**Comment by smummolo** [comment]
yes thats smart and im dumb for not building that in.

**Comment by CodySwannGT** [comment]
Ok cool. So do you want to leave as is for MVP?

**Comment by smummolo** [comment]
if you can add the third option easily then do it - if not, then leave it out. your call depending on LOE

**Comment by adamespn** [comment]
@smummolo This will be easy enough for me because the behavior will be driven by the API calls Cody supplies. @CodySwannGT Can you get me calls by Thursday morning?

**Comment by CodySwannGT** [comment]
Will do

**Comment by CodySwannGT** [comment]
The API will now accept "push" for challengers_proposed_outcome and opponents_proposed_outcome
