### ISSUE TITLE
Are there any safeguards against dumbasses?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#19]
The way the spec has it drawn up, I can accept any and all challenges and never get a loss just by disagreeing with the outcome that the creator chose.

Is that OK?

**Comment by DaryMerckensGT** [comment]
"If the challenger and the opponent agree on the outcome, that is the outcome. If they don't agree, it's a push"

Did I miss a new version of the spec? Because that's the dumbest fucking thing I've ever heard.

**Comment by CodySwannGT** [comment]
@smummolo - I'm fine with closing. Just something I thought of.

**Comment by smummolo** [comment]
im not sure we're going to figure this out right now but i see your point, something to watch for sure

**Comment by adamespn** [comment]
This is closed by new bet result screens
