### ISSUE TITLE
How do you change your Public/Private setting?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#2]
This was not addressed in the specs

**Comment by CodySwannGT** [comment]
This was not addressed in the specs

**Comment by smummolo** [comment]
tapping on the 3 dots (as the owner of the war) should essetially take you back to the authoring screen to edit that setting - for now you shouldnt be able to change anything else on that screen, but if thats too hard to limit, then we should at least notify the other party that a change has been made and prompt them to accept the war again

**Comment by CodySwannGT** [comment]
So obviously only the creator of the TW can edit the thumbwar. that much I know. 

But which ellipses are you referring to?

Right now, clicking the ellipses in feed mode takes you to detail view. 

Clicking ellipses in detail mode either opens the "pick winner" screen or alerts you that the TW still is pending. 

So can you explain under what conditions clicking the ellipses takes you to the edit screen?

**Comment by adamespn** [comment]
steve has an interesting idea in this ticket above "tapping on the 3 dots (as the owner of the war) should essetially take you back to the authoring screen to edit that setting", as it relates to anything war-related.

**Comment by jiakeliu** [comment]
Tapping on the ellipses should show a dropdown menu, and one of the options should be "Edit war privacy. Another Modal window with the title "Edit War Privacy" should pop up at this point with two choices:

Public
Participants Only

**Comment by jiakeliu** [comment]
@CodySwannGT @adamespn I remember seeing the Private/Public setting on the bet creation screen before, but it's taken out in the new releases. 

Was this feature ever implemented?

**Comment by CodySwannGT** [comment]
No. We punted on it a long time ago because there was no agreement on what
private actually meant and we deemed it not important for MVP

On Fri, May 8, 2015 at 8:12 PM, Jiake Liu <notifications@github.com> wrote:

> @CodySwannGT <https://github.com/CodySwannGT> @adamespn
> <https://github.com/adamespn> I remember seeing the Private/Public
> setting on the bet creation screen before, but it's taken out in the new
> releases.
>
> Was this feature ever implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/2#issuecomment-100397217>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by jiakeliu** [comment]
I see. Thanks for the clarification!

**Comment by jiakeliu** [comment]
Duplicate with #120 . Closing
