### ISSUE TITLE
How can I find ThumbWars that I haven't been accepted or rejected?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#20]
This was not addressed in the specs

**Comment by CodySwannGT** [comment]
@smummolo - just for clarification - this was mentioned as a pain point - being able to quickly find TWs that require a response. 

If this isn't core to mvp, that's fine. Just making sure.

**Comment by smummolo** [comment]
isnt this a great use for alerts section?

**Comment by CodySwannGT** [comment]
Works for me

**Comment by adamespn** [comment]
This should either be closed, or turn into some kind of server -side req for creating a new alert type.

**Comment by jiakeliu** [comment]
I agree that the Alerts screen is where the pending challenges should live. Here's a design mockup:

![alerts](https://cloud.githubusercontent.com/assets/1039583/7440599/d020dada-f073-11e4-9568-a2b3c5891f2a.jpg)

**Comment by adamespn** [comment]
Is this image supposed to contain a large gray rectangle?

**Comment by jiakeliu** [comment]
The gray rectangle is just the empty space in this view. What we currently have on the Alerts page is fine.

**Comment by adamespn** [comment]
There are additional specification and design decisions to be made on this ticket. Are you delegating them to me?

**Comment by jiakeliu** [comment]
There are a few other alert types, right? Let's leave those as is for now, and just add this challenge queue alert.

**Comment by adamespn** [comment]
For starters, suppose I have 3 unanswered wars and 2 wars that I started with Cody that he hasn't responded to. Under what circumstances do I see a notification for these and what happens when I click the buttons on it, both in this screen and on others?

**Comment by jiakeliu** [comment]
Good questions...let me think through these scenarios and come back to you. Let's focus on the UI/UX tickets in the 5.1-5.8 iteration and we will fit this ticket in one of our next iterations, after I've worked through the use cases.

**Comment by adamespn** [comment]
That's just one example question - there are others

**Comment by jiakeliu** [comment]
Yes, there are also:

-Someone followed you
-A Facebook friend joined Thumbwar
-Your opponent initiated to close a bet
-You won or lost a bet

Few others I'm sure. I'll think through them.

**Comment by adamespn** [comment]
Well, those are existing alerts. I'm solely thinking about the 2 kinds of notifications this tickets is in regards to and what the user experience is around them, not only when I'm staring at this screen, but when I start a new war, when I log in at a later time, when I open the war but do not dismiss it, how it relates to the popups we have for unanswered wars, badge counts changing when I receive a war and I'm in a modal screen, etc.  I assumed the logic for these two kinds of notifications was coming from the client side. Others come from the server side.

**Comment by adamespn** [comment]
Do you want to open a ticket for specifying this stuff and assign it to yourself?

**Comment by jiakeliu** [comment]
Suppose you have 3 unanswered wars and 2 wars that you started with Cody that he hasn't responded to:

The mockup above should address the use case for the 3 unanswered wars that were started by Cody. The badge should always display a number (in this case, 3) until you either accept or decline the wars. Just opening the war or any other actions should not change the badge count.

For the 2 wars that you started with Cody, there shouldn't be any alerts on your screen, but we should add a Pending Wars screen that houses these wars that you can access via Profile/Settings page. I will create a separate ticket for this.

**Comment by adamespn** [comment]
The mockup above shows exactly one notification and no "old-style" alerts, so I am not understanding how it addresses the use case for the 3 unanswered wars. Again, I'm happy to figure it out on my own.

**Comment by jiakeliu** [comment]
We will keep the "old-style" alerts as they are. 

The mockup reflects a war that Jiake Liu has challenged you to, that you have not responded yet.

For the 3 unanswered wars from Cody, the alert in the mockup would just repeat 3 times, stacked on top of each other in the feed view. Does that clarify?

**Comment by jiakeliu** [comment]
Here's the mockup for 3 unanswered wars:
![alerts_multiple](https://cloud.githubusercontent.com/assets/1039583/7481454/d76abeec-f324-11e4-81c7-72c272081a51.jpg)

**Comment by adamespn** [comment]
so these would always be above all "old-style" alerts no matter the date? I'm assuming they would scroll as well?

**Comment by jiakeliu** [comment]
Yes, and yes.

**Comment by adamespn** [comment]
I like Randy's comment on #96 - seems more natural

**Comment by jiakeliu** [comment]
@husseinm designs in this ticket should be used for the Alerts screen implementation.

**Comment by husseinm** [comment]
@CodySwannGT Can we remove the opened field from alerts (I see no use, but could be wrong).

Also can we only send unread notifications to the client, this way when a user uses the app for a long period of time and has 1000 notifications, they don't have to wait for a huge request to finish.

**Comment by husseinm** [comment]
@jiakeliu @CodySwannGT Adding the "X Hours ago" feature would require the server to send that information to me, do we still want that? If so, Cody can you add that information for me?

**Comment by husseinm** [comment]
@jiakeliu I have the X button completed, but would it be more intuitive for the user to simply swipe left to reveal a delete button, or just swipe to delete - as Apple does in the mail app?

**Comment by jiakeliu** [comment]
Discussed and agreed to keep X button for now

**Comment by husseinm** [comment]
@jiakeliu I am about to push to TF - this issue is almost complete, only missing the date (x hours ago, will have to talk to @CodySwannGT about that) and the view challenge button. Do we still want that button? If you press the alert it will still bring you to the challenge regardless... If so how do I take care of that, should we make the cell only view challenge on the press of the button or still anywhere on the cell except for the x? I also need the high res comment bubbles (50x50)...

Tickets #135 #134 #91 #118 #123 #77 #139 and everything we discussed this morning should be included in this release. Deploying right now...

**Comment by husseinm** [comment]
Should be fixed by the latest release.
