### ISSUE TITLE
How to we make alerts like in the spec?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#22]
There are a lot of items in the spec like this:

https://www.dropbox.com/s/mu0sl9xymonv7t7/Screenshot%202015-01-30%2020.45.13.png?dl=0

Have you guys ever seen an app do that? We're having a tough time figuring that out.

**Comment by smummolo** [comment]
if these style alerts are proving too challenging (or we were high when we imagined them) - the main idea is that alerts happen - if implementing standard iOS app alerts with custom language is more doable then lets do that - the alerts can just drive the user back to their notifications screen to take action
