### ISSUE TITLE
How do we implement the buttons on this screen?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#23]
This was not addressed in the mocks or design

![screenshot 2015-01-30 20 46 05](https://cloud.githubusercontent.com/assets/292923/5986307/35e80a96-a8c1-11e4-872c-b81ad2fa90de.png)

**Comment by smummolo** [comment]
do you need a visual design for this screen? (sorry if it was left out)
The intention was that this is an overlay alert that tells the user who won the challenge and presents them with options for next steps.

**Comment by CodySwannGT** [comment]
Yeah. Definitely would like a design of possible. 

Also a description of how a user gets to this screen and what happens when each button is clicked.

**Comment by smummolo** [comment]
the idea was that when you log into the app - and there is a resolution to a war you are involved in - you would get this alert, dismiss it or take action, if there are multiple, then they go in succession, until all gone. Not sure if randy has banddwith to mock

**Comment by CodySwannGT** [comment]
@adamespn can you use existing design patterns to fudge this for now?

**Comment by adamespn** [comment]
The simplest way t do this is to have it come from the "A war you are participating in just ended" because server-side persistence would be necessary. Otherwise, yes, I can guess at how this might work

**Comment by adamespn** [comment]
I am reopening this.
Unfortunately in testing this I ran across an edge case and I can't reliably know whether this alert has been shown before. This results in the user getting a very annoying number of these alerts even after having gotten them before. I have left the code intact but disconnected it from the app. We will need to readdress the design for a future iteration.

If anyone disagrees with this, I can easily reconnect the code for evaluation.

Moving to backlog.

**Comment by jiakeliu** [comment]
Not sure if related to the multiple alerts bug you are seeing, but here's a short Vine video of a bug I'm seeing with the ever increasing number of alerts each time I pull-refresh the Alerts page (pay attention to the notification badge on the Alerts tab):

https://vine.co/m/ANDHFm_IhhDXFwB7MidW2u2n3-ZdXpf_

**Comment by adamespn** [comment]
That looks like a bug (not related to anything else). Good find.
If you add a ticket I will fix that one first thing on Monday.

**Comment by jiakeliu** [comment]
Ok, created a new ticket: #72 

Back to this ticket, do we have a stating version where we can test the app before production push? I can't tell whether this is a code bug or a design issue. Could you elaborate on the issue?

**Comment by adamespn** [comment]
We have very poor requirements.

First we have a wireframe-ish screen with some unintelligible text - no visual design.

Then we have a brief statement that this should come up any time a war ends.

No use cases, no design, no examples. No narrative.

So, I really don't know exactly when it actually should pop up and when it shouldn't and what it should do.

Also, there should be some kind of limitation on on how many of these I might see at any given time. The alerts screen is where I would expect to get most of this information.

So, the bottom line is that this feature hasn't been thought through. If you can think it through and design a great user experience, then we can implement it precisely and we will all be very happy.

**Comment by adamespn** [comment]
I am trying to figure out how to invite you to test flight so you can pull down versions as we go. It doesn't always want to invite people who already have apple IDs. Stay tuned.

**Comment by adamespn** [comment]
OK - I see you are already in the tester list. Can you tell me what you mean by "staging version" if you don't mean test flight?

**Comment by jiakeliu** [comment]
Never mind about the staging version, for some reason I thought we are on App Store. TestFlight as it is works.

I will work on the UX for closing a bet and the subsequent notification. Will followup on this ticket.

**Comment by adamespn** [comment]
This is superseded by the new bet result screens
