### ISSUE TITLE
Clicking ellipses on war detail causes app to crash

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#31]
In the pictured screen shot, the user clicking the dots was not involved at all with the TW, so they shouldn't even see it.

![img_4365](https://cloud.githubusercontent.com/assets/292923/5986997/a8998184-a8e2-11e4-8775-66fc13a1a06f.PNG)

**Comment by adamespn** [comment]
I believe you should still see the war result - probably just a bug checking player 1 and player 2 against the current player
