### ISSUE TITLE
How do we handle a thumbwar with a white photo?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#35]
This wasn't in teh spec, but any photo with white in it hides the text..

**Comment by adamespn** [comment]
That was mentioned as a possibility - need a design decision - not a bug

**Comment by CodySwannGT** [comment]
@smummolo - got anything?

**Comment by smummolo** [comment]
sorry been off the grid - getting back into this today - simplest solution is to overlay a semi transparent black gradient over every image but we'll need to send you mocks / assets for this to explain - it wont be noticeable in dark images but will provide enough contrast on light images if implemented correctly to always be able to read the text - ill add it to randy's list

**Comment by adamespn** [comment]
Can you also look at #56 and tell me which way we should go here?

**Comment by CodySwannGT** [comment]
On hold for response to #56

**Comment by adamespn** [comment]
@smummolo Can you look at #56 and clarify the approach here?
