### ISSUE TITLE
Why are we allowing a photo to be uploaded WITH a thumbwar?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#36]
Not sure I understand the purpose here.

I thought the photo/video was "proof" - if so, why allow it to be uploaded with the initial challenge?

**Comment by smummolo** [comment]
its fun. this was an attempt to add a visual element to make the posts more interesting from the beginning

The proof image use case is if the challenge is happening RIGHT NOW (edge case i suppose)

**Comment by adamespn** [comment]
This is irrelevant now
