### ISSUE TITLE
Thumbwar fails to get created under these conditions

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#37]
1) Fill in what
2) Fill in "who"
3) Leave "Prize" blank
4) Hit submit
5) App warns you about validations errors
6) Enter "Prize"
7) Hit submit
8) App says thumbwar is created, but never shows up

**Comment by adamespn** [comment]
Does never mean never, like after a pull to refresh or quitting (home home  swipe up) app and running again?

**Comment by CodySwannGT** [comment]
Yes. Never means never.

Additionally, the two pickers unhide themselves. I tried to fix that with
some code cleanup, but no joy.

On Sat, Jan 31, 2015 at 11:08 PM, adamespn <notifications@github.com> wrote:

> Does never mean never, like after a pull to refresh or quitting (home home
> swipe up) app and running again?
>
> > On Jan 31, 2015, at 10:37 PM, Cody Swann <notifications@github.com>
> wrote:
> >
> > 1) Fill in what
> > 2) Fill in "who"
> > 3) Leave "Prize" blank
> > 4) Hit submit
> > 5) App warns you about validations errors
> > 6) Enter "Prize"
> > 7) Hit submit
> > 8) App says thumbwar is created, but never shows up
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/37#issuecomment-72350597>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
Ok. If it says it created a war then that means the server responded appropriately. Maybe just a problem with the war data.

**Comment by adamespn** [comment]
When do pickers unhide themselves? And is it during POST or during TUTORIAL?

**Comment by CodySwannGT** [comment]
I think it's better if you just go through the steps. It replicates every time.
