### ISSUE TITLE
Should you be able to change sides in a thumbwar? If so, how?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#39]
This isn't addressed in the spec.

**Comment by smummolo** [comment]
Yes - just tap the other one

**Comment by CodySwannGT** [comment]
@adamespn - is that enough info to plan out? Do you need more detail from Steve?

**Comment by adamespn** [comment]
It's enough info for UI requirements. I need to ask you how to accomplish this though the API. If I switch sides to I DELETE the original "following" before POSTing a new "following"? Or should the "following" get changed (or just left alone)?

**Comment by CodySwannGT** [comment]
Per API Docs
- POST /thumbwars/:thumbwar_id/unwatch
- POST /thumbwars/:thumbwar_id/watch (side)

**Comment by adamespn** [comment]
Do you want to work out all the watch/unwatch/side/inside/switch sides flows - would the following/unfollowing flows be impacted?

**Comment by CodySwannGT** [comment]
Not sure what you mean

On Saturday, February 14, 2015, adamespn <notifications@github.com> wrote:

> Do you want to work out all the watch/unwatch/side/inside/switch sides
> flows - would the following/unfollowing flows be impacted?
>
>
>
>
> > On Feb 14, 2015, at 12:28 AM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Per API Docs
> >
> > POST /thumbwars/:thumbwar_id/unwatch
> > POST /thumbwars/:thumbwar_id/watch (side)
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74379235>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
Example: can I watch a war without siding with a player?

**Comment by CodySwannGT** [comment]
No. Which is why "side" is a required parameter.

On Saturday, February 14, 2015, adamespn <notifications@github.com> wrote:

> Example: can I watch a war without siding with a player?
>
>
>
> > On Feb 14, 2015, at 11:54 AM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Not sure what you mean
> >
> > On Saturday, February 14, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Do you want to work out all the watch/unwatch/side/inside/switch sides
> > > flows - would the following/unfollowing flows be impacted?
> > >
> > >
> > >
> > >
> > > > On Feb 14, 2015, at 12:28 AM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > Per API Docs
> > > >
> > > > POST /thumbwars/:thumbwar_id/unwatch
> > > > POST /thumbwars/:thumbwar_id/watch (side)
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74379235
> >
> > > .
> > >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> > files and/or email messages attached to it, is intended for the sole use
> of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any dissemination
> or
> > copying of this communication is STRICTLY PROHIBITED. In such case please
> > notify the sender by reply email and delete this message without reading,
> > printing or saving.*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74382732>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
So then the call should be called "side" not "watch".

**Comment by CodySwannGT** [comment]
I don't think the name of an end point really matters.

I described it as I'm "watching this bet on Dary's side"

On Saturday, February 14, 2015, adamespn <notifications@github.com> wrote:

> So then the call should be called "side" not "watch".
>
>
>
> > On Feb 14, 2015, at 12:01 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > No. Which is why "side" is a required parameter.
> >
> > On Saturday, February 14, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Example: can I watch a war without siding with a player?
> > >
> > >
> > >
> > > > On Feb 14, 2015, at 11:54 AM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > Not sure what you mean
> > > >
> > > > On Saturday, February 14, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > Do you want to work out all the watch/unwatch/side/inside/switch
> sides
> > > > > flows - would the following/unfollowing flows be impacted?
> > > > >
> > > > >
> > > > >
> > > > >
> > > > > > On Feb 14, 2015, at 12:28 AM, Cody Swann <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>> wrote:
> > > > > >
> > > > > > Per API Docs
> > > > > >
> > > > > > POST /thumbwars/:thumbwar_id/unwatch
> > > > > > POST /thumbwars/:thumbwar_id/watch (side)
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74379235
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > > --
> > > > Cody Swann - CEO, Gunner Technology
> > > > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');> |
> www.gunnertech.com
> > > > <http://www.gunnertech.com/>Skype: cody.swann
> > > >
> > > > *CONFIDENTIALITY NOTICE: This email message, together with any
> documents,
> > > > files and/or email messages attached to it, is intended for the sole
> use
> > > of
> > > > the individual or entity to whom it is addressed, and may contain
> > > > information that is legally privileged, confidential and restricted
> from
> > > > disclosure. If you are not the intended recipient, or responsible for
> > > > delivery to that person, you are hereby notified that any
> dissemination
> > > or
> > > > copying of this communication is STRICTLY PROHIBITED. In such case
> please
> > > > notify the sender by reply email and delete this message without
> reading,
> > > > printing or saving.*
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74382732
> >
> > > .
> > >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> > files and/or email messages attached to it, is intended for the sole use
> of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any dissemination
> or
> > copying of this communication is STRICTLY PROHIBITED. In such case please
> > notify the sender by reply email and delete this message without reading,
> > printing or saving.*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74382946>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
It matters quite a bit when you say things like "Per the API docs". Anybody reading the API call signature will believe this call is for watching was, and - without any other description of the endpoint to fall back on - will use the call incorrectly.

This has already happened at least once or twice.

Now, I'm pretty sure the original intention of this call is to "watch", not "side". "Side" was was added to that call in v2. 

Are we never going to watch thumbwars without siding? Because it would be better to figure that out ahead of time and save a few hours of work that could be applied to some other feature.

**Comment by CodySwannGT** [comment]
As of right now, there is no plans to watch a tw without a side. If that
ever changes, the side parameter will no longer be required.

On Saturday, February 14, 2015, adamespn <notifications@github.com> wrote:

> It matters quite a bit when you say things like "Per the API docs".
> Anybody reading the API call signature will believe this call is for
> watching was, and - without any other description of the endpoint to fall
> back on - will use the call incorrectly.
>
> This has already happened at least once or twice.
>
> Now, I'm pretty sure the original intention of this call is to "watch",
> not "side". "Side" was was added to that call in v2.
>
> Are we never going to watch thumbwars without siding? Because it would be
> better to figure that out ahead of time and save a few hours of work that
> could be applied to some other feature.
>
>
>
> > On Feb 14, 2015, at 12:07 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I don't think the name of an end point really matters.
> >
> > I described it as I'm "watching this bet on Dary's side"
> >
> > On Saturday, February 14, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > So then the call should be called "side" not "watch".
> > >
> > >
> > >
> > > > On Feb 14, 2015, at 12:01 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > No. Which is why "side" is a required parameter.
> > > >
> > > > On Saturday, February 14, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > Example: can I watch a war without siding with a player?
> > > > >
> > > > >
> > > > >
> > > > > > On Feb 14, 2015, at 11:54 AM, Cody Swann <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>> wrote:
> > > > > >
> > > > > > Not sure what you mean
> > > > > >
> > > > > > On Saturday, February 14, 2015, adamespn <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>> wrote:
> > > > > >
> > > > > > > Do you want to work out all the
> watch/unwatch/side/inside/switch
> > > sides
> > > > > > > flows - would the following/unfollowing flows be impacted?
> > > > > > >
> > > > > > >
> > > > > > >
> > > > > > >
> > > > > > > > On Feb 14, 2015, at 12:28 AM, Cody Swann <
> > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>
> > > > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');>');>>
> wrote:
> > > > > > > >
> > > > > > > > Per API Docs
> > > > > > > >
> > > > > > > > POST /thumbwars/:thumbwar_id/unwatch
> > > > > > > > POST /thumbwars/:thumbwar_id/watch (side)
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub.
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > >
> > >
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74379235
> > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Cody Swann - CEO, Gunner Technology
> > > > > > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');>
> > > > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');>');> |
> > > www.gunnertech.com
> > > > > > <http://www.gunnertech.com/>Skype: cody.swann
> > > > > >
> > > > > > *CONFIDENTIALITY NOTICE: This email message, together with any
> > > documents,
> > > > > > files and/or email messages attached to it, is intended for the
> sole
> > > use
> > > > > of
> > > > > > the individual or entity to whom it is addressed, and may contain
> > > > > > information that is legally privileged, confidential and
> restricted
> > > from
> > > > > > disclosure. If you are not the intended recipient, or
> responsible for
> > > > > > delivery to that person, you are hereby notified that any
> > > dissemination
> > > > > or
> > > > > > copying of this communication is STRICTLY PROHIBITED. In such
> case
> > > please
> > > > > > notify the sender by reply email and delete this message without
> > > reading,
> > > > > > printing or saving.*
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74382732
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > > --
> > > > Cody Swann - CEO, Gunner Technology
> > > > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');> |
> www.gunnertech.com
> > > > <http://www.gunnertech.com/>Skype: cody.swann
> > > >
> > > > *CONFIDENTIALITY NOTICE: This email message, together with any
> documents,
> > > > files and/or email messages attached to it, is intended for the sole
> use
> > > of
> > > > the individual or entity to whom it is addressed, and may contain
> > > > information that is legally privileged, confidential and restricted
> from
> > > > disclosure. If you are not the intended recipient, or responsible for
> > > > delivery to that person, you are hereby notified that any
> dissemination
> > > or
> > > > copying of this communication is STRICTLY PROHIBITED. In such case
> please
> > > > notify the sender by reply email and delete this message without
> reading,
> > > > printing or saving.*
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74382946
> >
> > > .
> > >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> > files and/or email messages attached to it, is intended for the sole use
> of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any dissemination
> or
> > copying of this communication is STRICTLY PROHIBITED. In such case please
> > notify the sender by reply email and delete this message without reading,
> > printing or saving.*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74383353>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
My crystal ball says that will change very soon.

**Comment by adamespn** [comment]
Second example: can I just stop siding with a player without switching sides?

**Comment by CodySwannGT** [comment]
@adamespn I opened new issue to address that #66

**Comment by bobagahi** [comment]
I read some of these comments.  I dont think it should be a necessity for everyone to side with one person or the other.  They can if they want to but they dont have to.  (I think most people will) but on instagram you can scroll and watch without siding.  I also think that for a future version release that if you tap one side you can see all the usernames that sided with that side and vice versa.  Sort of like when you are on instagram and you click the "57 likes" text and you can see all 57 people that liked the photo.  People are curious like that.  Makes it more fun.

**Comment by CodySwannGT** [comment]
Here's the way I see it (in the future)

Three levels of involvement:

1) Be involved in the TW
2) Take a side in the TW
3) Follow someone involved in the TW

I think if you add a fourth, it gets really superfluous

1) Be involved in the TW
2) Take a side in the TW
3) "Watch" a TW without choosing a side
4) Follow someone involved in the TW

It's kind of like - "Look, if you are interested in this particular TW,
don't be a little bitch and pick a side" I don't see the advantage of
having neutral onlookers.

On Wed, Feb 18, 2015 at 5:39 PM, bobagahi <notifications@github.com> wrote:

> I read some of these comments. I dont think it should be a necessity for
> everyone to side with one person or the other. They can if they want to but
> they dont have to. (I think most people will) but on instagram you can
> scroll and watch without siding. I also think that for a future version
> release that if you tap one side you can see all the usernames that sided
> with that side and vice versa. Sort of like when you are on instagram and
> you click the "57 likes" text and you can see all 57 people that liked the
> photo. People are curious like that. Makes it more fun.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/39#issuecomment-74963980>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
I agree with that, Cody.

The issue I have is that the notion of siding is very specific.

The notion of watching is less specific.

If you can't watch without siding then the UX gets a little odd.

So, I believe we should allow watching and then encourage siding. Most people will side.

**Comment by bobagahi** [comment]
Ok cool. Could be a very cool dynamic.
