### ISSUE TITLE
When I get a challenge from someone, it pops open automatically in the app, per spec, but shouldn't I be able to see who it's from?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#41]
![img_4754](https://cloud.githubusercontent.com/assets/292923/5991185/316ca23e-a9ab-11e4-8808-b590ba1b8883.PNG)

**Comment by smummolo** [comment]
Yes definitley - "your friend" should be he users name...

**Comment by CodySwannGT** [comment]
@adamespn - anything else you need to know here?

**Comment by adamespn** [comment]
Nope - i got it - next deploy - probably tomorrow or Thursday

**Comment by adamespn** [comment]
This change is pushed. I'm not going to bother deploying a new app to test flight for just this. Tomorrow I will got through the tickets that can be scheduled and schedule a deployment.
