### ISSUE TITLE
Files are taking too long to upload

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#43]
I believe this is because we are converting all files to pngs, which is increasing their size exponentially and the heroku servers timeout uploading them. Let's change it to a jpeg with compression.

**Comment by adamespn** [comment]
Can you post some typical sizes of these files?

**Comment by CodySwannGT** [comment]
Simple fix. And it worked as expected. Upload times are now down about 120%.

**Comment by adamespn** [comment]
Does have heroku have any SLAs around this kind of stuff?

**Comment by CodySwannGT** [comment]
https://devcenter.heroku.com/articles/request-timeout

On Tue, Feb 3, 2015 at 8:46 PM, adamespn <notifications@github.com> wrote:

> Does have heroku have any SLAs around this kind of stuff?
>
> > On Feb 3, 2015, at 8:43 PM, Cody Swann <notifications@github.com> wrote:
> >
> > Simple fix. And it worked as expected. Upload times are now down about
> 120%.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/43#issuecomment-72775095>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*
