### ISSUE TITLE
Logic for Accepted and Rejecting challenges is in correct

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#44]
This needs to get fixed ASAP.

In BetResponse.swift, you are setting the status of the thumbwar object itself as "accepted" or "rejected".

This is actually a clear violation of the API.

The valid parameters for a PUT /thumbwars/:id are:

:challenger_id
:body
:expires_in
:wager
:opponents_proposed_outcome (enum 'win' | 'loss' ) (defaults to nil)
:challengers_proposed_outcome (enum 'win' | 'loss' ) (defaults to nil)
:photo
:remote_photo_url
:url (not used)
:publish_to_twitter (not used) 
:publish_to_facebook (not used)

The status of a thumbwar is managed internally and should never be set by the client.

CHALLENGES should be accepted or rejected as spelled out in the API here: https://github.com/gunnertech/thumbwar-api/tree/fresh#challenge

**Comment by adamespn** [comment]
No problem. In the future, having a specific set of use cases and clearly tying the specific sequence of API calls to each use case would prevent any confusion or "illegal" use of API calls, which is critical, especially in cases where making the "wrong" call produces the expected result, as this call does. The ios-client change will get pushed later today.

**Comment by CodySwannGT** [comment]
I agree with that.

On Wed, Feb 4, 2015 at 7:16 PM, adamespn <notifications@github.com> wrote:

> No problem. In the future, having a specific set of use cases and clearly
> tying the specific sequence of API calls to each use case would prevent any
> confusion or "illegal" use of API calls, which is critical, especially in
> cases where making the "wrong" call produces the expected result, as this
> call does. The ios-client change will get pushed later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/44#issuecomment-72969646>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
fixed and committed, not pushed or tested

**Comment by adamespn** [comment]
fixed and pushed - not tested
