### ISSUE TITLE
Bet Response should have the names of the actual participants

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#45]
Right now, it just says "User 1" and "Opponent"

The buttons should have:

"Cody Swann"

"Adam Meikle"

 
![img_4813](https://cloud.githubusercontent.com/assets/292923/6049997/29d101f0-ac8a-11e4-82b0-640b0531ff3c.PNG)

**Comment by adamespn** [comment]
It was broken, although I don't see how it could have said "User 1" or "Opponent" so we might need to track that down. Fix applied (not pushed yet)

**Comment by adamespn** [comment]
committed, not pushed or tested

**Comment by adamespn** [comment]
Verified fixed on IOS8.1/iPhone 6. Ready to deploy

**Comment by CodySwannGT** [comment]
Cool. When you push to github, use commit message "closes #45" and this ticket will automatically close
