### ISSUE TITLE
YES / NO Buttons

### ISSUE THREAD

**Issue by smummolo** [gunnertech/thumbwar-ios-client#46]
the words "yes" / "no" are confusing because they seem to answer a questions - i know this has been an issue that we've been wrestling with forever. 

What do you think about just making the buttons Green (check) / Red (x) for now and losing the words all together?

Alternate would be to put a simple instruction above the buttons: "Do you accept this war?" in fact - that might work great - thoughts?

Just a thought I had this morning while using the app...

**Comment by DaryMerckensGT** [comment]
Search your email archive for an email with the subject line "FW: **TW Designs" where we had an extended discussion about this very topic. My view is summed up by this reply of mine:

> Regardless of language, just think red vs green, negative vs positive, with a negative assertion, what do those two responses mean.
> 
> "Someone can't do something."
> 
> Green response - positive, they can, directing the positivity at the someone.
> 
> or
> 
> Green response - positive, they can't, directing the positivity at the assertion.
> 
> And this isn't resolved by more explicitly directing the response, by saying something like "Agree with the thumbwar" or "Approve this thumbwar", because the way our brain processes that, it's still not solidified whether my response is to the thumbwar or the object of the thumbwar.
> 
> So if there's a word that captures that, this solution might be tenable. But that's still TBD and until that word is found, if such a word exists, this solution is dead in the water.

**Comment by adamespn** [comment]
What's wrong with

"George Washington has challenged you to a thumbwar. Do you accept?"

....
Details
...

"I accept! Bring it!"
"No way! What fool would take that bet?"

**Comment by CodySwannGT** [comment]
I don't think it matters what we go with here.

Per Steve's previous statements, it is assumed that the challenger and the opponent have other recourse outside of thumbwar to clarify and understand each other, so the way I see this going is:

To Steve:

"Cody has challenged you to a thumbwar. Do you accept?"

"The Red Sox didn't have a black player until the 1970s"

"I accept! Bring it!"
"No way! What fool would take that bet?"

Steve sends a text message to Cody:

"Dude, are you betting me that the Red Sox did or didn't have a black player until the 1970s?"



"Steve has challenged you to a thumbwar. Do you accept?"

"Three people are going to die on Sons of Anarchy tonight"

"I accept! Bring it!"
"No way! What fool would take that bet?"

Steve sends a text message to Cody:

"Dude, are you betting me that at least three people are going to die on sons of anarchy?"

Before Steve clarified this, I was thinking Thumbwar was for more serendipitous challenges/predictions/bets with people you may or may not be in close communication with.

However, now that Steve has clarified that the challenger and opponent are assumed to have communication outside of TW, we could literally make the choices "Hippo" and "Pony"

Example:

"Dary challenged you to a thumbwar!"

"I can eat an entire bowl of pasta"

"Hippo"
"Pony"

Cody to Dary: "Dude, if I click 'Hippo' am I saying I agree that you can eat a whole bowl of pasta?"

Dary to Cody: "Nah, dude. If you think I can eat a whole bowl of pasta, click 'Pony'".

**Comment by adamespn** [comment]
Cody to Dary: "What the hell is the matter with these people. Why did they put hippo and pony on here?"

Dary to Cody: "I don't know man, it took me forever to figure that out the first time. I think these people are crazy"

**Comment by CodySwannGT** [comment]
Ok. So let's do this:

@smummolo - can you have Randy mock up what you have in mind and we'll go with that to at least get out of the gate. Then deal with any confusion from public feedback.

**Comment by smummolo** [comment]
Yep



On Feb 8, 2015, at 7:36 AM, Cody Swann <notifications@github.com> wrote:

Ok. So let's do this:

@smummolo - can you have Randy mock up what you have in mind and we'll go with that to at least get out of the gate. Then deal with any confusion from public feedback.

**Comment by smummolo** [comment]
all i want is simple white text above the buttons that says:

"Do you accept this Thumb War?"

**Comment by adamespn** [comment]
OK
