### ISSUE TITLE
The circular avatars on completed TWs should be live and go to a profile

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#47]
The circular avatars on completed TWs should be live and go to a profile, more content about the people who are betting.  The circular avatars should also have names under them so that if you are scrolling you can see who bet who instead of just the pic vs pic.  I think the (  ) vs (  ) is important to interact with.  Right now the globe page and home page that show completed TWs are pretty static.  Would be cool to see who the people are betting.  Discover.

**Comment by adamespn** [comment]
Is this assigned to anybody?

**Comment by CodySwannGT** [comment]
Yes. Steve

**Comment by smummolo** [comment]
this is another good note and will require a design revision, for now lets leave it and put it on the list for the next version.

**Comment by adamespn** [comment]
I'm hearing we should do nothing here.

**Comment by smummolo** [comment]
nothing please

**Comment by adamespn** [comment]
Closing as duplicate
