### ISSUE TITLE
Need follow feature

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#48]
On profiles, can we "follow this users TWs"?  Lets say Lebron James signs up, it would be great to follow all his bets.  His (public) TWs can then go on the globe page with all tws you follow.  (*I know this is a feature but somewhat relevant to my earlier comment thats why its here).

**Comment by adamespn** [comment]
Is this assigned to anybody?

**Comment by CodySwannGT** [comment]
No. It's not active. We're waiting on Steve to chime in

**Comment by smummolo** [comment]
not for MVP but a key feature for the next round

**Comment by adamespn** [comment]
I'm hearing we should do nothing here.

**Comment by smummolo** [comment]
do nothing thx
