### ISSUE TITLE
Comment tweaks

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#49]
the three button link next to the comments section I think is unnecessary to have Just that as the link to make comments.  That whole bar should be live.  Click on "comments" and the whole bar there and you can comment.  Its less difficult if its that way.  If its just the three dots, then its harder to hit and more confusing.  Should be more simple.  The whole bar is live.

**Comment by smummolo** [comment]
change the three dots to a comment bubble icon. you can also put the number of comments in that bubble if you want to get fancy. 

The idea behind the three dots was that there would be additional functionality and detail in that view but for now it seems like overkill and i agree its hard to tap right now

**Comment by adamespn** [comment]
We have a bubble on the left side at this time. We also have the number of comments shown as well. Should any of that change or should we add a second bubble?

**Comment by smummolo** [comment]
sorry - think the one bubble is enough maybe just move it to the right and call it a day

**Comment by jiakeliu** [comment]
Should we retain the three dots, even as a placeholder, for additional functionalities down the line such as following, reporting, and sharing a post? 

I think it's quite intuitive to touch the chat bubble on the left side OR anywhere on the post to see the expanded post/comment view.

**Comment by adamespn** [comment]
There are other tickets that refer to other parts of the post being touched. Can you take a look before finalizing changes to this ticket?

**Comment by jiakeliu** [comment]
I see another ticket that refers to touching the avatars. Any other parts on the screen that can be touched?

**Comment by adamespn** [comment]
Just confirming before I close this - we are leaving everything as is, but we are allowing you to touch anywhere (except when a separate ticket conflicts) to open comments.

**Comment by jiakeliu** [comment]
Yes, anywhere but the portraits. Can you put in a placeholder drop-down
list for the three dots? We will add follow, report, and other
functionalities down the line. For now the list options don't have to do
anything or we can add a modal window that says "Coming soon". Your choice.

**Comment by adamespn** [comment]
If the ellipses won't be functional then we should remove them, because - frankly - they are darn near impossible to tap as it is. A great way to PO the user would be to give them a button that is hard to tap and then have it say "under construction" or whatever.

**Comment by jiakeliu** [comment]
Ok, lets remove the ellipses for now.
