### ISSUE TITLE
Siding

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#50]
Right now you can only Side with one person when you are in the comments section and its open.  Makes no sense.  You should have one - tap siding functionality from the globe and home page.  Makes no sense to only have that ability from the comment page.  ALSO - the %s you see are not visible on any other section unless you are in the comment section.  That obviously needs to change so that if 90% agree with Alex vs Bob on a TW, on the home or globe page, it says 90% in Alex's avatar and 10% in bobs.  right now it only does that if you are in comments section of the particular TW.  so two points here.  1.  should see the %s on all screens as to what the siding consensus is.  2.  You should be able to one-tap your vote on who you like from home and globe sections as well as comment section.

**Comment by adamespn** [comment]
Just a quick note - I added the %s in the war detail screen (as discussed in the original release notes) as a clue that this is where you could "side" with someone.
I see this ticket has been unassigned. What is the current status?

**Comment by CodySwannGT** [comment]
assigned to steve

**Comment by smummolo** [comment]
agree - the intention was to be able to side from the feed page sorry if that wasnt clear. 

the percentages are nice - move them to the feed - they should appear when you tap to pick a side on the global and home feeds

**Comment by adamespn** [comment]
"they should appear when you tap..." Does this mean the percentages should not be shown unless you tap one of the avatars?

Consider the following use case:
1) User opens war X
2) user sides with someone
3) User closes app
4) User opens app
5) User views war X in feed (or opens)
6) User taps avatar to side with other party

At what points in this flow should percentages be shown/not shown?

**Comment by smummolo** [comment]
percentages should be shown all the time - the number is less important than the circle graph. cool if they can update in real time post tap, if not, next time the feed is refreshed is an acceptable 2nd

**Comment by adamespn** [comment]
OK so basically make the avatars in the feed view exactly like the avatars in the war detail? Percent AND circle graph? Or no circle graph? @smummolo

**Comment by CodySwannGT** [comment]
Exactly the same with circle graph

**Comment by jiakeliu** [comment]
One tap on a portrait should lead to the user profile, so the tap to side is kind of unintuitive.

As mentioned in #75, let's try using the swipe or slide gesture to side. Eg. Swipe left on a post to side with left user, swipe right to side with right user.

**Comment by adamespn** [comment]
Moving to backlog, per Jiake and my convo about user profiles and search

**Comment by jiakeliu** [comment]
(Deleted a duplicated ticket and merging into this one)

The current way of siding by touching portrait conflicts with the action of looking up user profile.

Mimicking the action of siding with chips on a gambling table (slide the chips to an area on the table), users can side bets on the Home screen or in a post by sliding a knob or a chip to either participant on opposite sides.

The portraits and usernames of whom have taken a side will display in the comment section on either the left or the right side. Will followup with design mockup.

**Comment by adamespn** [comment]
Should this be closed?

**Comment by jiakeliu** [comment]
I'd love some user feedback on the slider. I'm not in love with it and think there maybe a better/more intuitive way of siding. Let's keep this open for now and move it to Backlog.

**Comment by adamespn** [comment]
I love the slider but the built in iOS slider sucks.

Let's re-engineer it at some point

**Comment by jiakeliu** [comment]
In the War Detail screen, let's remove the sliding bar at the top. Instead,change the texts "Side with User A" and "Side with User B" in the "Siding" tab into clickable links that accomplishes the same thing as siding. Does that make sense, @husseinm?

**Comment by husseinm** [comment]
Sure.
