### ISSUE TITLE
When creating a TW the back arrow button is key.  You get stuck in it otherwise.  When I type in the @prize field, the keyboard blocks the field itself and I cant see what I am typing. 

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#51]

**Comment by smummolo** [comment]
the fields screen should scroll up as they get filled in so that the field you are typing in is visible OR i should be able to pull the screen up to show it.

That said - on my i6 i dont have this issue at all and can see all fields all the time.

**Comment by smummolo** [comment]
the nav bar is present at the bottom so im not sure how you get stuck without an arrow? That said if you want to add one at the top go ahead :)

**Comment by adamespn** [comment]
@smummolo @CodySwannGT I will try this o an iPhone 5 on Monday. I can't picture the issue you are speaking of. However, I'm sure there is a standard way to handle this. I will let you know if there are any problems.

**Comment by adamespn** [comment]
Cannot reproduce on iPhone 5s - see attached screenshot - Cody please close unless you have new information
![iphone5skeybboard](https://cloud.githubusercontent.com/assets/1437020/6536773/616ec8a8-c41e-11e4-8d09-224a75fb6dbe.png)

**Comment by CodySwannGT** [comment]
See that white bar? Expand that and you can reproduce the problem
