### ISSUE TITLE
Facebook is great but we should have a feature to just add in a phone number or username.  Because on the spot challenges may take time with people that you are not already friends with on FB.  (feature?)

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#53]

**Comment by smummolo** [comment]
this seems to be searching my fb and my ab so that covers people i know. Can you just put in the ability to type a phone number and not call it out for now? I think it's an edge case BUT also intuitive enough that people are going to do it anyway

**Comment by adamespn** [comment]
@CodySwannGT @smummolo if you type a phone number in and no user with that phone number exists, what do I use for a user name (or display name or first name or last name) when I create the user? Can you have a user with no name? Does this only work for 10 digit USA phone numbers?

**Comment by CodySwannGT** [comment]
So this would have to be different from the lookahead because we can't give out phone numbers.

The implementation would have to be an exact match.

Here is how it works:

1) User types in a phone number but no suggestions come up.
2) The mobile number is considered valid if it has at least 10 digits
3) If no country code is specified, "1" is assumed
4) When the user hits the Submit button to finalize the war, the app must first call out to the /users API endpoint and pass the mobile number as the search parameter (see api docs for more info)
5) The api will return an array of either 1 or 0. If the array is 0, there is no user with that mobile number and the creation should fail with an error message: "There is no user with that phone number" - otherwise, the matching user should be set as the challenger

**Comment by adamespn** [comment]
Ok got it so it's just like typing a name only we are searching based on a number and we won't create a user with only a phone number.

**Comment by CodySwannGT** [comment]
exactly

On Fri, Feb 27, 2015 at 11:56 PM, adamespn <notifications@github.com> wrote:

> Ok got it so it's just like typing a name only we are searching based on a
> number and we won't create a user with only a phone number.
>
>
>
> > On Feb 27, 2015, at 11:53 PM, Cody Swann <notifications@github.com>
> wrote:
> >
> > So this would have to be different from the lookahead because we can't
> give out phone numbers.
> >
> > The implementation would have to be an exact match.
> >
> > Here is how it works:
> >
> > 1) User types in a phone number but no suggestions come up.
> > 2) The mobile number is considered valid if it has at least 10 digits
> > 3) If no country code is specified, "1" is assumed
> > 4) When the user hits the Submit button to finalize the war, the app
> must first call out to the /users API endpoint and pass the mobile number
> as the search parameter (see api docs for more info)
> > 5) The api will return an array of either 1 or 0. If the array is 0,
> there is no user with that mobile number and the creation should fail with
> an error message: "There is no user with that phone number" - otherwise,
> the matching user should be set as the challenger
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/53#issuecomment-76510720>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*
