### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#55]
Counter.  It really should be accept, decline and counter.  you should be able to modify the bet itself (I bet I can do 100 push ups, and the person you bet counters and says 150) OR you challenge whats at stake, the prize (bet you that the suns win tonight) for 10$, you counter back for 50$ and then the original challenger can then accept decline or counter again. (I know this is a feature but its very important to have in the first version at least I feel).

**Comment by smummolo** [comment]
counter was left out of MVP on purpose-  but agree we should get there.

**Comment by adamespn** [comment]
So, I'm hearing that we should do nothing as of right now

**Comment by smummolo** [comment]
do nothing
