### ISSUE TITLE
The Alerts page

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#60]
The Alerts page is boring and I think it should show the actual comment or a teaser of it instead of the standard "alex posted a comment" and then you have to go see it.  Maybe down the road.

**Comment by smummolo** [comment]
agree - this is the simple version - eventually it would be nice to make it more interactive and robust for sure

**Comment by adamespn** [comment]
So, I'm hearing that we should do nothing as of right now

**Comment by smummolo** [comment]
correct - do nothing
