### ISSUE TITLE
How do completed and closed out thumbwars get archived?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#61]

**Comment by smummolo** [comment]
they should appear in the "my wars" section of your profile - listed under won/lost/all etc...

**Comment by adamespn** [comment]
What is an "archived" thumb war, exactly?

**Comment by smummolo** [comment]
we don't have to archive wars, they just go into your "my wars" section and can be found chronologically

**Comment by CodySwannGT** [comment]
OK. So an archived TW is the same as an unarchived TW.

**Comment by smummolo** [comment]
yes 

     On Monday, March 9, 2015 12:44 PM, Cody Swann <notifications@github.com> wrote:
   

 OK. So an archived TW is the same as an unarchived TW.—

**Comment by adamespn** [comment]
Ok so I will do nothing and close this ticket
