### ISSUE TITLE
Bug: Alerts badge infinite increment on pull-refresh

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#72]
Video of the bug in action (pay attention to the notification badge on the Alerts tab): 
[https://vine.co/m/ANDHFm_IhhDXFwB7MidW2u2n3-ZdXpf_](https://vine.co/m/ANDHFm_IhhDXFwB7MidW2u2n3-ZdXpf_)

Summary:
Ever increasing number of alerts each time user pull-refreshes the Alerts page.

Repro:
When there is a new alert, go to the Alerts page and pull-refresh repeatedly.

**Comment by adamespn** [comment]
Cannot reproduce against build 22

**Comment by adamespn** [comment]
As suspected, this is a repeatable issue with fresh installs of build 22 but SHOULD NOT have been.
Current build does not show this behavior - confirming just to be sure on all platforms
