### ISSUE TITLE
Replace the "X" button with back arrow

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#73]
Instead of the "X" button on the top right of the post, let's use a white back arrow icon on the top left of the post. Functionality should not be changed.

**Comment by adamespn** [comment]
Does anybody want to specify the look and feel of the arrow or will anything do?

**Comment by jiakeliu** [comment]
How about this in white: http://fortawesome.github.io/Font-Awesome/icon/arrow-left/

**Comment by jiakeliu** [comment]
In build 25, the "X" is still present instead of the back arrow.
