### ISSUE TITLE
Initiate bet closure (Declare Winner)

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#75]
Only the participants can initiate to close a bet by declaring the results.

In the post view, when either participant touches the ellipses, there should be an option of "Declare Winner". After selecting it, this is the screen that shows up:
![declarewinner](https://cloud.githubusercontent.com/assets/1039583/6800767/d162fa76-d1de-11e4-973d-f90d2c5e90ea.png)
After submission, the opponent will then have a chance to react to the declaration. Will followup with a separate ticket and refer it here.

**Comment by jiakeliu** [comment]
Per phone conversation with @adamespn, we've decided to hold off on implementing the "slide to bet" mechanism. Let's use the tap to select winner on this screen for now, just like siding bets in a post currently.

**Comment by adamespn** [comment]
Jiake, let's catch up on this on Monday morning. I thought you were talking about something else with "slide"

**Comment by jiakeliu** [comment]
Did you think I meant Tinder's swiping? What do you think about this kind of sliding? A visual example is something like this: http://drbl.in/eeCR

**Comment by jiakeliu** [comment]
Attaching mock up from Randy:

![whowon](https://cloud.githubusercontent.com/assets/1039583/6951985/bde6851c-d873-11e4-92d1-4eb69cff233f.png)

**Comment by jiakeliu** [comment]
How can I see this screen? Currently when I click the ellipses on a bet, it jumps directly to "User says you won(lost) the bet!" and I can choose "Yes" or "No".

**Comment by jiakeliu** [comment]
Need to get to this screen from the Bet Detail view's ellipses.

**Comment by jiakeliu** [comment]
@husseinm the correct flow for war closure is this:

1. Either participant taps ellipses in the War Detail view, a drop-down menu appears with an item "Declare Winner" 
2. User A taps "Declare Winner" and the mockup in this ticket appears, asking User A who won the war. At this point User A can say he won the war, his opponent won the war, or that it was a draw. He may also attach comment or image in the declaration.
3. Say in the previous step User A said he won the war, User B gets a push notification saying "User A declared a winner on a Thumbwar with you", upon tapping the notification, User B sees the view in #78 mockup.
4. User B can agree/disagree by tapping yes/no. If he agrees, the war finishes, and the final winner screen appears (to be mocked-up). If he disagrees, he is presented with the "Declare Winner" screen in this ticket.
