### ISSUE TITLE
Bet creation screen revamp

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#76]
The bet creation process should be intuitive, so we should mirror the layout to an actual post.
![creation](https://cloud.githubusercontent.com/assets/1039583/6809179/d54de6c8-d215-11e4-8d83-8c7b380f48ec.png)

**Comment by adamespn** [comment]
OK - I think I get this and I think I love the design. See comments in other tickets

**Comment by jiakeliu** [comment]
Attaching mock up from Randy:

![creation](https://cloud.githubusercontent.com/assets/1039583/6951963/a992bd9c-d873-11e4-8b8d-0b964a838d92.png)

**Comment by adamespn** [comment]
Quick note on this: On the top line, where it has an avatar, "You", a text field with the opponent name, and another avatar - this does not fit well - the opponent's name is always cut off. I'm going to mess with it a little at some point.

**Comment by jiakeliu** [comment]
Let's replace the top bar with just a text field with the default text "Who are you betting?"

**Comment by jiakeliu** [comment]
@adamespn can we please remove the left profile picture, "You", and the right profile picture, and leave the "vs Name" text field in the first row of this screen? Replace "vs Name" default text with "Who are you betting?"

**Comment by adamespn** [comment]
ok
