### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#77]
Users should be able to search by thumbwar content or user.
![search](https://cloud.githubusercontent.com/assets/1039583/7002371/5b05f066-dbfe-11e4-86f8-a859d0a46d31.png)

**Comment by jiakeliu** [comment]
![search](https://cloud.githubusercontent.com/assets/1039583/7014184/75838e58-dc76-11e4-9f06-dfe1b95b83cf.jpg)

**Comment by jiakeliu** [comment]
![suggestions_v2](https://cloud.githubusercontent.com/assets/1039583/7014191/8bb93f92-dc76-11e4-91c2-e17f235c5379.jpg)

**Comment by adamespn** [comment]
Jiake, when you choose to search contacts, Facebook, or twitter (which we are not integrated with), how does that experience differ from searching for registered thumb war users?

**Comment by jiakeliu** [comment]
For a LIVE example, check out Polar https://itunes.apple.com/us/app/polar/id563322683?mt=8 Go to the Home feed, and click on the Search manifying glass on the top left corner, and click "People".

When a user picks Facebook or Twitter, the app would ask permission (first time) to connect to their respective social account and search and return other Thumbwar users that connected their social accounts.

The Search field in the mockup doesn't really tie in with the four Facebook, Twitter, Contacts, and Suggested buttons, because when you search for a user the app should return Thumbwar users directly agnostic to which source they signed up with. 

Does that clarify?

**Comment by adamespn** [comment]
No.

**Comment by jiakeliu** [comment]
Search field returns all relevant TW users.

Facebook button returns Facebook friends that are TW users.
Twitter button returns Twitter followers/followings that are TW users.
Suggested button returns a list of users curated by us.

**Comment by adamespn** [comment]
Ok. So exactly the same as what happens when you type a name in the post screen.

Do we have a method for curating users or is that for a future release?

**Comment by jiakeliu** [comment]
Essentially, yes. The only difference from the post screen is that instead of a drop down menu of users, the users in the Search screen show up on a scrollable list. And we don't care which source a user comes from. 

Eg. typing in "Adam" just returns "adamespn" and any other users that have "adam" in their username, but not "TW: adamespn" "FB: adamespn"

**Comment by adamespn** [comment]
Why is there a Facebook button in that case?

**Comment by jiakeliu** [comment]
The Facebook button is essentially a query that says "return all users that are my friends on Facebook" without having to type in any names. It's a feature to find all your Facebook friends on Thumbwar without you knowing in the first place. Does that make sense?

**Comment by adamespn** [comment]
yes

**Comment by adamespn** [comment]
Can you layout the use case where a user logs in to twitter? or should that button be disabled?

**Comment by adamespn** [comment]
searching for wars pulls up the equivalent of a home screen?

**Comment by jiakeliu** [comment]
Let's gray out the Twitter button for now. 

But use case should be similar to Facebook when we come around to implementing it. Eg. Asks user permission to connect TW to their Twitter account and queries "return all users that I'm following or are my followers on Twitter".

**Comment by jiakeliu** [comment]
Yes, eauivalent to home screen.

**Comment by CodySwannGT** [comment]
Here is what was decided:

1) Lose Wars: This means dropping the Users | Wars toggle and the text box should just say "Search Users"

2) Twitter and Suggested are grayed out / inactive

3) Contacts loads all your contacts

4) Facebook loads only your Facebook friends who also have authorized Thumbwar

**Comment by husseinm** [comment]
Status?

**Comment by jiakeliu** [comment]
Cody's last comment still needs to be implemented. Let me know if you need elaboration.

**Comment by jiakeliu** [comment]
@husseinm I don't like how the screen is currently laid out. Can we lose the "Search" button and use the magnifying glass icon at the right of the search bar instead?

Also, can we move "Search for friends via:" along with the 4 buttons to the top of the screen like shown in the mockup?
