### ISSUE TITLE
Bet closure opponent screen

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#78]
After a bet closure/winner declaration is initiated by one party (#75) the opponent has a chance to acknowledge or reject the declaration.

Will followup with design mockup.

**Comment by jiakeliu** [comment]
Here's the mockup

![opponent](https://cloud.githubusercontent.com/assets/1039583/6844072/16aaa9de-d366-11e4-921b-628dd7ead506.png)

**Comment by adamespn** [comment]
Question: Where does the text come from? Or did I miss something in a other screen?
Maybe a flow that shows the lifecycle of bet creation and finalization showing the copy traveling from one screen to the next would clarify. Good design though.

**Comment by jiakeliu** [comment]
Good idea. Here's the particular UX flow. Hope it makes sense:

![uxflow](https://cloud.githubusercontent.com/assets/1039583/6880577/ed0f1a7e-d4f5-11e4-81ba-dac654c8e84c.png)

**Comment by jiakeliu** [comment]
Attaching mock up from Randy:

![results](https://cloud.githubusercontent.com/assets/1039583/6952012/ecd1dcdc-d873-11e4-81a3-b9b3efeea964.png)

**Comment by jiakeliu** [comment]
@husseinm this ticket should provide you with more details about the Who Won and Results page implementation. Reopening.
