### ISSUE TITLE
Revamped bottom nav bar 

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#84]
Consolidate "Home" and "Global" into one home feed. Add "Search" view as defined in #77 

![bottomnav](https://cloud.githubusercontent.com/assets/1039583/7002510/dde47f64-dc00-11e4-88c9-0962bb602360.png)

**Comment by jiakeliu** [comment]
![tabbar_v2](https://cloud.githubusercontent.com/assets/1039583/7016036/55cd10e0-dc92-11e4-991d-69a86a528c5d.jpg)

**Comment by jiakeliu** [comment]
Please update the UI to match this design. No text at the bottom of the icons and the "Create War" button should be a "+" sign not the crossed swords.

**Comment by jiakeliu** [comment]
@adamespn please reopen this issue, as it's part of the UI/UX fix for this week.

**Comment by adamespn** [comment]
I'm using the post icon V1 instead of V3
