### ISSUE TITLE
Performance: address book look up slow down

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#86]
On the post creation screen, looking up a contact slows the app down considerably when the address book is huge. This happened to Josh's iPhone 6. 

While we are at this, @adamespn, currently if I type a contact name, the drop down shows "TW: Name" and "FB: Name". Can we consolidate the two and just show one name? The user usually doesn't care where the contact comes from, as long as they can get to the right person.

**Comment by husseinm** [comment]
Does this still exist? I am having absolutely no slowdown in my simulator, but I only have a limited address book and a Quad-core i7... Would have to test after Testflight tomorrow...

**Comment by jiakeliu** [comment]
This only seems to happen when the address book has a lot of contacts. I will test it again after this release and get back to you.

**Comment by jiakeliu** [comment]
Asking Josh to reproduce this issue.

**Comment by husseinm** [comment]
Tested it with 1000 contacts - was fast enought
