### ISSUE TITLE
How to I follow/unfollow another user?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#9]
This was not addressed in the spec. Nor is there anyway to search for a user

**Comment by smummolo** [comment]
this was left out in this version (though its important to get to later) the idea was to really strip this mvp down to basics for now and this didnt make the cut

**Comment by CodySwannGT** [comment]
Ok. So what's the difference between the globe and home tab?

On Friday, February 6, 2015, smummolo <notifications@github.com> wrote:

> this was left out in this version (though its important to get to later)
> the idea was to really strip this mvp down to basics for now and this didnt
> make the cut
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/9#issuecomment-73277290>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by smummolo** [comment]
for right now - global is all public wars, home is wars you are involved in. this is not the intended final functionality just the basic first step

**Comment by CodySwannGT** [comment]
Gotcha.

On Friday, February 6, 2015, smummolo <notifications@github.com> wrote:

> for right now - global is all public wars, home is wars you are involved
> in. this is not the intended final functionality just the basic first step
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/9#issuecomment-73277919>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*
