### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#90]
Use the existing Thumbwar background for the loading screen which is currently black.

**Comment by husseinm** [comment]
Closing this issue, the ThumbWar loading screen has this.

**Comment by jiakeliu** [comment]
@husseinm when the loading process is slow (heroku dyno spin-up), you would see the black screen and the loading icon. We need to replace this black screen with the Thumbwar background and the loading icon.

**Comment by husseinm** [comment]
Should be corrected by the latest update.

**Comment by jiakeliu** [comment]
I still saw the black loading screen this morning : 
![file jun 08 6 36 24 pm](https://cloud.githubusercontent.com/assets/1039583/8048980/746f2400-0e0d-11e5-9c9b-fe7cc31dce5b.png)

**Comment by husseinm** [comment]
I mean this update coming up.

**Comment by jiakeliu** [comment]
Oh okay, great!

**Comment by husseinm** [comment]
I just pushed to TestFlight so you can see this and the comment issues resolved.

**Comment by jiakeliu** [comment]
Fixed! Closing.

**Comment by jiakeliu** [comment]
@husseinm the black loading screen is back again in the new version. Can you fix?
