### ISSUE TITLE
Search users should only display TW users

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#91]
Currently the Search Users feature returns people from the local address book. Please limit the search to all TW users. The use case here is for me to find other TW users to follow/view.

**Comment by husseinm** [comment]
Isn't this already implemented?

**Comment by jiakeliu** [comment]
In the current version, when you search for a user, only local contacts are returned in the results. It should instead return registered TW users.

**Comment by husseinm** [comment]
The search function currently only works for Facebook ids (perfect for the Facebook friends functionality, works well). Since we are given a name and told to search for that I am going to need the database to index the names for speed and have the server search the First/Last name columns for the API search method.

**Comment by CodySwannGT** [comment]
Couple things

* The API /users?search=<string> will return matches for email, mobile number and username. So /users?search=codyswann will return me.

* I'm going to implement this such that First Name will be everything Before the last space and Last name will be everything after the last space.

search=?Mary%20Beth%20Leonard will perform a search where(first_name == 'Mary Beth' && last_name == 'Leonard')

**Comment by CodySwannGT** [comment]
deploying now. Will require the parsed string to have a first name and last name

**Comment by husseinm** [comment]
@jiakeliu would that be okay - a user can only be searched for by BOTH first and last?
On Jul 10, 2015 6:23 PM, Cody Swann <notifications@github.com> wrote:deploying now. Will require the parsed string to have a first name and last name

**Comment by husseinm** [comment]
It should also already be in the current build not front end changes
On Jul 10, 2015 6:23 PM, Cody Swann <notifications@github.com> wrote:deploying now. Will require the parsed string to have a first name and last name

**Comment by CodySwannGT** [comment]
Actually, I'll just make it so that if there is no space, it will search only first name

**Comment by jiakeliu** [comment]
Can we implement fuzzy search so even if I just type Mah it will return
Mahdi Hussein?

On Friday, July 10, 2015, Cody Swann <notifications@github.com> wrote:

> Actually, I'll just make it so that if there is no space, it will search
> only first name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/91#issuecomment-120545414>
> .
>


-- 
Sent from Gmail Mobile

**Comment by CodySwannGT** [comment]
Sure

On Fri, Jul 10, 2015 at 7:01 PM, Jiake Liu <notifications@github.com> wrote:

> Can we implement fuzzy search so even if I just type Mah it will return
> Mahdi Hussein?
>
> On Friday, July 10, 2015, Cody Swann <notifications@github.com> wrote:
>
> > Actually, I'll just make it so that if there is no space, it will search
> > only first name
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/91#issuecomment-120545414
> >
> > .
> >
>
>
> --
> Sent from Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/91#issuecomment-120547344>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by CodySwannGT** [comment]
deploying now

**Comment by jiakeliu** [comment]
@CodySwannGT is fuzzy search in place? When I type in "Mah" Mahdi doesn't show up in the search results

**Comment by jiakeliu** [comment]
Fixed!
