### ISSUE TITLE
Remove the "$" sign in the prize/stake field

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#93]
Currently when I type anything in the Prize/Stake field in the bet creation screen, a "$" sign appears in front of the text automatically. Please remove this.

Maybe related, it looks like if I type "$5" as the Prize, the "$" sign doesn't actually show up in the bet after it's created.

**Comment by adamespn** [comment]
@CodySwannGT the server strips any $ in the prize field. Can you remove that function?

**Comment by adamespn** [comment]
On a related note - if I don't have a dollar sign in the prize, does that impact the notion of searching for hashtags and dollar signs?

**Comment by jiakeliu** [comment]
The Prize field should allow for free form text. The "$" hashtag Cody mentioned should be implemented differently that's outside the scope of this ticket. Let's not worry about the "#" or "$" in the MVP.
