### ISSUE TITLE
Update bet creation tutorial screen

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#94]
Bet creation tutorial screen should match the default bet creation screen.

**Comment by adamespn** [comment]
Are you asking me to decide what "match" means?

**Comment by jiakeliu** [comment]
The current tutorial screen still reflects the old bet creation screen, right?

**Comment by adamespn** [comment]
In the sense that somebody created a sequence of TUTORIAL screens that were hoped to seem a lot like the POST screen, that is true.

There is no deterministic function that takes the POST screen as input and automatically specifies a TUTORIAL screen. The TUTORIAL screen has its own needs.

For example, if a text box on the POST screen is near the top of the screen, that box would be moved down on the tutorial screen to account for the fact that a nice label is being put over it.

So it's only as simple as saying "Make this screen look like the new POST screen" IF you are delegating the design decisions to me.

Steve and company produced 9 wireframes or so for tutorial design.

**Comment by jiakeliu** [comment]
I see. 

Let's make the UI update on the bet creation screen (Issue 76) first, and then we will come back to the tutorial screen. I will work on the design mockup.

**Comment by jiakeliu** [comment]
Let's take out the tutorial screen and land the user directly at the Home feed. I think the bet creation screen is intuitive/explanatory enough and the tutorial screen is just repeating what the default text says.

**Comment by jiakeliu** [comment]
@husseinm please take out the tutorial screen as part of the onboarding flow. It's very buggy and we want to land user directly on the content and not creation.

**Comment by husseinm** [comment]
@CodySwannGT I removed all the relevant client side code and will release that today, can you remove the Tutorial alert from the server side?

**Comment by CodySwannGT** [comment]
deploying now. 3 minutes

On Sat, Jun 20, 2015 at 3:00 PM, Mahdi Hussein <notifications@github.com>
wrote:

> @CodySwannGT <https://github.com/CodySwannGT> I removed all the relevant
> client side code and will release that today, can you remove the Tutorial
> alert from the server side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/94#issuecomment-113804693>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by husseinm** [comment]
Thanks!
