### ISSUE TITLE
Feed view UI update

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#95]
![feed_v7](https://cloud.githubusercontent.com/assets/1039583/7459357/13a42e50-f250-11e4-8b54-d6f8c22bcdf3.jpg)

"1 min" - time stamp
Speech bubble - comment count (tapping here goes to the bet detail view with the comment text field active/keyboard up)
Heart - "likes" count (tapping here "likes" the post, tapping again reverses the like)
Medal ribbon logo - prize/stake field. If the text gets too long, use "..." at the end. (tapping here expands the prize field vertically to display all text)

Link to PSD: https://www.dropbox.com/s/slb9sqc09th0bmh/feed_v7.psd?dl=0

**Comment by adamespn** [comment]
Where does the "heart" icon count come from?

**Comment by jiakeliu** [comment]
The heart count comes from people that like a post. Do we need to create a separate ticket to implement this on the server side, @CodySwannGT?

**Comment by CodySwannGT** [comment]
@jiakeliu yes plase

**Comment by jiakeliu** [comment]
Let's hold off on implementing the "Like" feature.

@adamespn, please update the feed UI to match the mockup and take away the Heart icon and counter for now, instead just show the comment icon and counter aligned to the right.

**Comment by husseinm** [comment]
We implemented most of these features in the update
