### ISSUE TITLE
Match the App design to the PSDs

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#99]
There are way too many discrepancies right now to create a ticket for each difference, so please go through each PSD and make the app match the design, using autolayout to solve screen size differences.

**Comment by husseinm** [comment]
Forgot to mention, the photoshop files I received have several fonts I do not have. I am simply substituting the fonts I am seeing for Helvetica Neue as of right now...

Not sure if we can get this done by Wednesday, I will try and am on track right now, planning on finishing the New War/Post page today... Tomorrow I can give a better status on whether we may need to push to the next iteration, hopefully not.

**Comment by CodySwannGT** [comment]
Thanks man. Wednesday is a check-in meeting. We wouldn't be looking to have this done until Friday - but, same thing stands.

We know that there is a lot of discrepancies from the PSDs, so if you need to spill into the next iteration, that's fine, too.
